# Generated by Django 4.0.2 on 2022-04-01 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_userconsultant_personal', models.BooleanField(default=False)),
                ('is_userconsultant_company', models.BooleanField(default=False)),
                ('consultant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_contactnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_email', models.CharField(blank=True, max_length=200, null=True)),
                ('consultantpersonal_about', models.TextField(blank=True, null=True)),
                ('consultantpersonal_presentaddress', models.TextField(blank=True, null=True)),
                ('consultantpersonal_permanentaddress', models.TextField(blank=True, null=True)),
                ('consultantcompany_primarycontract_name', models.CharField(blank=True, max_length=200, null=True)),
                ('consultantcompany_primarycontract_number', models.CharField(blank=True, max_length=200, null=True)),
                ('consultantcompany_primarycontract_email', models.CharField(blank=True, max_length=200, null=True)),
                ('consultantcompany_about', models.TextField(blank=True, null=True)),
                ('consultantcompany_reg_officeaddress', models.TextField(blank=True, null=True)),
                ('consultantcompany_presentaddress', models.TextField(blank=True, null=True)),
                ('consultantcompany_website', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_company_fblink', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_company_linkedinlink', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_service_category', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_servicelocation', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_servicebudget_startrange', models.IntegerField(blank=True, null=True)),
                ('consultant_servicebudget_endrange', models.IntegerField(blank=True, null=True)),
                ('consultant_servicedescription', models.TextField(blank=True, null=True)),
                ('consultant_servicedetail_filepath', models.FileField(blank=True, null=True, upload_to='user/consultant_servicedetail_file')),
                ('consultant_cvpath', models.FileField(blank=True, null=True, upload_to='user/consultant_cv')),
                ('consultant_idverification_type', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_idverification_passportimagepath', models.ImageField(blank=True, null=True, upload_to='user/consultant_idverification_passportimage')),
                ('consultant_tin', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_bin', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_otherpermits', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_bankaccount', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_bankaccount_number', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_bankaccount_branchnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_bankaccount_swiftcode', models.CharField(blank=True, max_length=200, null=True)),
                ('consultant_bankaccount_routingnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_consultancydata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultancyTimeSchudile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultancy_timeschudile_startdate', models.DateField(blank=True, null=True)),
                ('consultancy_starttime', models.TimeField(blank=True, null=True)),
                ('consultancy_endtime', models.TimeField(blank=True, null=True)),
                ('consultancy_rate', models.IntegerField(blank=True, null=True)),
                ('is_consultancy_take', models.BooleanField(default=False)),
                ('consultancyid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultancy_timeschudile', to='consultancy_app.consultancycreate')),
            ],
        ),
        migrations.CreateModel(
            name='UserConsultAppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_request_datetime', models.DateTimeField(auto_now_add=True)),
                ('appointment_seeker_requested_datetime', models.DateTimeField()),
                ('appointment_attendent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_seeker_cellphone', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_seeker_email', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_seeker_note', models.TextField(blank=True, null=True)),
                ('appointment_seeker_starrating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('appointment_seeker_starrating_comment', models.TextField(blank=True, null=True)),
                ('consultant_provider_starratting', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('consultant_provider_starratting_comment', models.TextField(blank=True, null=True)),
                ('reason_for_missing_appointment', models.TextField(blank=True, null=True)),
                ('ConsultancyTimeSchudileid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='consultancy_timeschudile', to='consultancy_app.consultancytimeschudile')),
                ('seekerid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
