# Generated by Django 4.0.2 on 2022-04-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_app', '0002_remove_userconsultappointmentrequest_consultancytimeschudileid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconsultappointmentrequest',
            old_name='ConsultancyTimeSchudileil',
            new_name='ConsultancyTimeSchudile',
        ),
    ]
