# Generated by Django 4.0.2 on 2022-04-02 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_app', '0003_rename_consultancytimeschudileil_userconsultappointmentrequest_consultancytimeschudile'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancycreate',
            name='digitalservice_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='educationService_degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='legalcivilservice_issue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='legalcivilservice_required',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='medicalconsultancyservice_treatment_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='overseasrecruitmentservice_job_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='propertymanagementservice_need',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='propertymanagementservice_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='tourismservices',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='tradefacilitationservice_Purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='tradefacilitationservice_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='trainingservice_duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='trainingservice_topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userconsultappointmentrequest',
            name='ConsultancyTimeSchudile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy_app.consultancytimeschudile', unique=True),
        ),
    ]
