# Generated by Django 4.0.2 on 2022-04-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_app', '0006_rename_district_consultancycreate_propertymanagementservice_propertylocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsultappointmentrequest',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
