# Generated by Django 4.0.2 on 2022-04-05 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_app', '0007_userconsultappointmentrequest_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconsultappointmentrequest',
            name='consultancy_id',
        ),
    ]
