# Generated by Django 4.0.2 on 2022-04-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_app', '0010_alter_prouserpayment_verify_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(blank=True, max_length=200, null=True)),
                ('val_id', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('card_type', models.CharField(blank=True, max_length=200, null=True)),
                ('store_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('card_no', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_tran_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('tran_date', models.CharField(blank=True, max_length=200, null=True)),
                ('error', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('card_issuer', models.CharField(blank=True, max_length=200, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('card_sub_brand', models.CharField(blank=True, max_length=200, null=True)),
                ('card_issuer_country', models.CharField(blank=True, max_length=200, null=True)),
                ('card_issuer_country_code', models.CharField(blank=True, max_length=200, null=True)),
                ('store_id', models.CharField(blank=True, max_length=200, null=True)),
                ('verify_sign', models.CharField(blank=True, max_length=200, null=True)),
                ('verify_key', models.TextField(blank=True, null=True)),
                ('verify_sign_sha2', models.TextField(blank=True, null=True)),
                ('currency_type', models.CharField(blank=True, max_length=200, null=True)),
                ('currency_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('currency_rate', models.CharField(blank=True, max_length=200, null=True)),
                ('base_fair', models.CharField(blank=True, max_length=200, null=True)),
                ('value_a', models.CharField(blank=True, max_length=200, null=True)),
                ('value_b', models.CharField(blank=True, max_length=200, null=True)),
                ('value_c', models.CharField(blank=True, max_length=200, null=True)),
                ('value_d', models.CharField(blank=True, max_length=200, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=200, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=200, null=True)),
                ('risk_title', models.CharField(blank=True, max_length=200, null=True)),
                ('UserConsultAppointmentRequest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy_app.userconsultappointmentrequest')),
            ],
        ),
    ]
