# Generated by Django 4.0.2 on 2022-04-10 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultancy_app', '0014_rename_userconsultappointmentrequest_consultancypayment_userconsult_appointmentrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultancypayment',
            old_name='userConsult_AppointmentRequest',
            new_name='consultancy_sheduleid',
        ),
        migrations.AddField(
            model_name='consultancypayment',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
