# Generated by Django 4.0.2 on 2022-04-11 09:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_app', '0015_rename_userconsult_appointmentrequest_consultancypayment_consultancy_sheduleid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancycreate',
            name='digitalservice_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultancycreate',
            name='educationService_degree',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultancycreate',
            name='legalcivilservice_issue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultancycreate',
            name='legalcivilservice_required',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultancycreate',
            name='medicalconsultancyservice_treatment_area',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultancycreate',
            name='overseasrecruitmentservice_job_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultancycreate',
            name='propertymanagementservice_need',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultancycreate',
            name='propertymanagementservice_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultancycreate',
            name='tourismservices',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultancycreate',
            name='tradefacilitationservice_Purpose',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultancycreate',
            name='tradefacilitationservice_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultancycreate',
            name='trainingservice_duration',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultancycreate',
            name='trainingservice_topic',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
