# Generated by Django 4.0.2 on 2022-02-27 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_socialaccount_and_about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_about', models.TextField(blank=True, null=True)),
                ('user_fbaccount', models.CharField(blank=True, max_length=200, null=True)),
                ('user_twitteraccount', models.CharField(blank=True, max_length=200, null=True)),
                ('user_instagramaccount', models.CharField(blank=True, max_length=200, null=True)),
                ('user_linkedinaccount', models.CharField(blank=True, max_length=200, null=True)),
                ('user_website', models.CharField(blank=True, max_length=200, null=True)),
                ('user_whatsapp_account', models.CharField(blank=True, max_length=200, null=True)),
                ('user_whatsapp_visibility', models.CharField(blank=True, max_length=200, null=True)),
                ('user_viber_account', models.CharField(blank=True, max_length=200, null=True)),
                ('user_immo_account', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
