# Generated by Django 4.0.2 on 2022-02-27 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_socialaccount_and_about',
            name='user_whatsapp_visibility',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='user_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('user_companyname', models.CharField(blank=True, max_length=200, null=True)),
                ('user_responsibilities', models.TextField(blank=True, null=True)),
                ('userexperience_startdate', models.DateField(blank=True, null=True)),
                ('userexperience_enddate', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
