# Generated by Django 4.0.2 on 2022-03-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0005_rename_user_user_education_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_idverification',
            name='user_verify_passportphoto_path',
            field=models.ImageField(blank=True, null=True, upload_to='user/ID_verification'),
        ),
    ]
