# Generated by Django 4.0.2 on 2022-03-01 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0002_remove_user_auth_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_durationyear_abroad',
            field=models.IntegerField(default=0),
        ),
    ]
