# Generated by Django 4.0.2 on 2022-03-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0004_alter_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photopath',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile_picture'),
        ),
    ]
