# Generated by Django 4.0.2 on 2022-03-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0005_alter_user_user_photopath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photopath',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
