# Generated by Django 4.0.2 on 2022-03-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0008_alter_user_user_photopath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_device_typeserial',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
