# Generated by Django 4.0.2 on 2022-03-28 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0021_alter_phoneotp_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 28, 11, 8, 29, 861910)),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='user_callphone',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
