# Generated by Django 4.0.2 on 2022-04-05 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0061_alter_phoneotp_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pro_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 13, 50, 30, 614373)),
        ),
    ]
