# Generated by Django 4.0.2 on 2022-04-05 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0065_alter_phoneotp_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro_user_created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 14, 29, 57, 99532)),
        ),
    ]
