# Generated by Django 4.0.2 on 2022-03-09 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_blog_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userblog_reaction', models.CharField(blank=True, max_length=200, null=True)),
                ('userblog_reactionpublisher_location', models.CharField(blank=True, max_length=200, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_blog_app.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
