# Generated by Django 4.0.2 on 2022-03-19 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_blog_app', '0009_alter_blog_reaction_blogid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_reaction',
            name='blogid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_reaction', to='user_blog_app.blog'),
        ),
        migrations.AlterField(
            model_name='blog_reaction',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_reaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
