# Generated by Django 4.0.2 on 2022-03-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog_app', '0002_blog_reaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='blog_comment',
            old_name='user',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='blog_reaction',
            old_name='user',
            new_name='userid',
        ),
    ]
