# Generated by Django 4.0.2 on 2022-03-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog_app', '0003_rename_user_blog_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='userblog_addphoto',
        ),
        migrations.AddField(
            model_name='blog',
            name='userblog_addphotopath',
            field=models.ImageField(blank=True, null=True, upload_to='blog/post_photo'),
        ),
    ]
