# Generated by Django 4.0.2 on 2022-03-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog_app', '0004_remove_blog_userblog_addphoto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_comment',
            old_name='userblog_comment',
            new_name='blogcomment',
        ),
        migrations.RenameField(
            model_name='blog_comment',
            old_name='userblog_commentpublisher_location',
            new_name='blogcomment_publisherlocation',
        ),
        migrations.RenameField(
            model_name='blog_comment',
            old_name='blog',
            new_name='blogid',
        ),
        migrations.RenameField(
            model_name='blog_reaction',
            old_name='blog',
            new_name='blogid',
        ),
        migrations.RemoveField(
            model_name='blog_reaction',
            name='userblog_reaction',
        ),
        migrations.RemoveField(
            model_name='blog_reaction',
            name='userblog_reactionpublisher_location',
        ),
        migrations.AddField(
            model_name='blog_reaction',
            name='is_user_dislike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog_reaction',
            name='is_user_like',
            field=models.BooleanField(default=False),
        ),
    ]
