# Generated by Django 4.0.2 on 2022-03-13 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_blog_app', '0005_rename_userblog_comment_blog_comment_blogcomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_reaction',
            name='blogid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_blog_app.blog', unique=True),
        ),
    ]
