# Generated by Django 4.0.2 on 2022-03-14 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_blog_app', '0006_alter_blog_reaction_blogid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='userblog_publishdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_blog', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='blogid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blog_comment', to='user_blog_app.blog'),
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog_reaction',
            name='blogid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_reaction', to='user_blog_app.blog', unique=True),
        ),
        migrations.AlterField(
            model_name='blog_reaction',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
