# Generated by Django 4.0.2 on 2022-03-13 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_connection_app', '0002_userconnectionrequestsend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnectionrequestsend',
            name='connection_request_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='connection_request_to', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
