# Generated by Django 4.0.2 on 2022-03-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_connection_app', '0006_rename_connection_request_note_userfavoutirerequestsend_favourite_request_note_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavoutirerequestsend',
            old_name='user',
            new_name='userid',
        ),
    ]
