# Generated by Django 4.0.2 on 2022-03-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_connection_app', '0009_userfavouritelist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavouritelist',
            old_name='favourite_request_to',
            new_name='favourite_userid',
        ),
    ]
