# Generated by Django 4.0.2 on 2022-04-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_connection_app', '0010_rename_favourite_request_to_userfavouritelist_favourite_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavouritelist',
            name='is_Report',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfavouritelist',
            name='is_unmatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfavouritelist',
            name='is_unread',
            field=models.BooleanField(default=False),
        ),
    ]
