# Generated by Django 4.0.2 on 2022-02-28 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userconsultant_type', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_contactnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_email', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_about', models.TextField(blank=True, null=True)),
                ('userconsultant_presentaddress', models.TextField(blank=True, null=True)),
                ('userconsultant_permanentaddress', models.TextField(blank=True, null=True)),
                ('userconsultant_primary_contractname', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_primary_contractnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_primary_email', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_registered_officeaddress', models.TextField(blank=True, null=True)),
                ('userconsultant_company_website', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_fblink', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_linkedinlink', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_service_category', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_servicelocation', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_servicebudget_startrange', models.IntegerField(blank=True, null=True)),
                ('userconsultant_servicebudget_endrange', models.IntegerField(blank=True, null=True)),
                ('userconsultant_servicedescription', models.TextField(blank=True, null=True)),
                ('userconsultant_servicedetail_filepath', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_cvpath', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_idverification_type', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_idverification_pasportimagepath', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_TIN', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_BIN', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_otherpermits', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_bankaccount', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_bankaccount_number', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_bankaccount_branchnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_bankaccount_swiftcode', models.CharField(blank=True, max_length=200, null=True)),
                ('userconsultant_bankaccount_routingnumber', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_consult_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_request_datetime', models.DateTimeField(auto_now_add=True)),
                ('appointment_seeker_requested_datetime', models.DateTimeField()),
                ('appointment_attendent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_seeker_cellphone', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_seeker_email', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_seeker_note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user_consultant_pk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_connection_app.user_consultant')),
            ],
        ),
    ]
