# Generated by Django 4.0.2 on 2022-03-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_connection_app', '0003_alter_userconnectionrequestsend_connection_request_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnectionrequestsend',
            name='connection_request_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
