# Generated by Django 4.0.2 on 2022-03-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_connection_app', '0005_rename_userconnectionrequestsend_userfavoutirerequestsend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfavoutirerequestsend',
            old_name='connection_request_note',
            new_name='favourite_request_note',
        ),
        migrations.RenameField(
            model_name='userfavoutirerequestsend',
            old_name='connection_request_to',
            new_name='favourite_request_to',
        ),
        migrations.RenameField(
            model_name='userfavoutirerequestsend',
            old_name='is_connection_accept',
            new_name='is_favourite_accept',
        ),
        migrations.RenameField(
            model_name='userfavoutirerequestsend',
            old_name='is_connection_reject',
            new_name='is_favourite_reject',
        ),
    ]
