# Generated by Django 4.0.2 on 2022-03-13 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultancy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancycreate',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_consultancydata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserConsultAppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_request_datetime', models.DateTimeField(auto_now_add=True)),
                ('appointment_seeker_requested_datetime', models.DateTimeField()),
                ('appointment_attendent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_seeker_cellphone', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_seeker_email', models.CharField(blank=True, max_length=200, null=True)),
                ('appointment_seeker_note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user_consultant_pk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy_app.consultancycreate')),
            ],
        ),
    ]
