# Generated by Django 4.0.2 on 2022-04-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconsultappointmentrequest',
            name='ConsultancyTimeSchudileid',
        ),
        migrations.RemoveField(
            model_name='userconsultappointmentrequest',
            name='appointment_seeker_requested_datetime',
        ),
        migrations.AddField(
            model_name='userconsultappointmentrequest',
            name='ConsultancyTimeSchudileil',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy_app.consultancytimeschudile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userconsultappointmentrequest',
            name='consultancy_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='consultancy_app.consultancycreate'),
            preserve_default=False,
        ),
    ]
