# Generated by Django 4.0.2 on 2022-03-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_app', '0002_alter_consultancycreate_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconsultappointmentrequest',
            name='appointment_seeker_starrating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='userconsultappointmentrequest',
            name='appointment_seeker_starrating_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userconsultappointmentrequest',
            name='consultant_provider_starratting',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='userconsultappointmentrequest',
            name='consultant_provider_starratting_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userconsultappointmentrequest',
            name='reason_for_missing_appointment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
