# Generated by Django 4.0.2 on 2022-03-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_app', '0003_userconsultappointmentrequest_appointment_seeker_starrating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconsultappointmentrequest',
            old_name='user_consultant_pk',
            new_name='providerid',
        ),
        migrations.RenameField(
            model_name='userconsultappointmentrequest',
            old_name='user',
            new_name='seekerid',
        ),
    ]
