# Generated by Django 4.0.2 on 2022-04-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_app', '0004_consultancycreate_digitalservice_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultancycreate',
            old_name='consultant_servicelocation',
            new_name='consultant_service_locationcountry',
        ),
        migrations.AddField(
            model_name='consultancycreate',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
