# Generated by Django 4.0.2 on 2022-03-19 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_app', '0004_rename_user_consultant_pk_userconsultappointmentrequest_providerid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconsultappointmentrequest',
            old_name='providerid',
            new_name='consultantid',
        ),
    ]
