# Generated by Django 4.0.2 on 2022-04-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultancy_app', '0005_rename_consultant_servicelocation_consultancycreate_consultant_service_locationcountry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultancycreate',
            old_name='district',
            new_name='propertymanagementservice_propertylocation',
        ),
    ]
