# Generated by Django 4.0.2 on 2022-03-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting_other_app', '0002_staticsettingdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticsettingdata',
            old_name='user_areaof_interest_data',
            new_name='user_areaof_experience_data',
        ),
    ]
