# Generated by Django 4.0.2 on 2022-03-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting_other_app', '0006_rename_promo_code_status_promo_code_data_is_promo_code_active_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='promo_code_data',
            table='promo_code_data',
        ),
    ]
