# Generated by Django 4.0.2 on 2022-03-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting_other_app', '0008_rename_promo_code_data_promocodedata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticsettingdata',
            name='user_education_data',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
