# Generated by Django 4.0.2 on 2022-03-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting_other_app', '0009_staticsettingdata_user_education_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facing_trouble',
            name='user_problem_photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='probashi_app/facing_trouble'),
        ),
    ]
