# Generated by Django 4.0.2 on 2022-03-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting_other_app', '0010_alter_facing_trouble_user_problem_photo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticsettingdata',
            name='faq_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='faq_title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='privacypolicy_descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='privacypolicy_title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
