# Generated by Django 4.0.2 on 2022-03-31 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_setting_other_app', '0011_staticsettingdata_faq_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_title', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('notification_description', models.TextField(blank=True, null=True)),
                ('is_notification_seen', models.BooleanField(default=False)),
                ('notification_date', models.DateTimeField(auto_now_add=True)),
                ('terget_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
