# Generated by Django 4.0.2 on 2022-04-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting_other_app', '0015_rename_user_user_settings_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticsettingdata',
            name='digitalservice_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='educationService_degree',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='legalcivilservice_issue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='legalcivilservice_required',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='medicalconsultancyservice_treatment_area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='overseasrecruitmentservice_job_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='propertymanagementservice_need',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='propertymanagementservice_propertylocation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='propertymanagementservice_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='tourismservices',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='tradefacilitationservice_Purpose',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='tradefacilitationservice_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='trainingservice_duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staticsettingdata',
            name='trainingservice_topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
