# Generated by Django 4.0.2 on 2022-04-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendSuggation',
        ),
    ]
