# Generated by Django 4.0.2 on 2022-04-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_chat_app', '0002_delete_friendsuggation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomGroupNameTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.CharField(max_length=20)),
                ('user_2', models.CharField(max_length=20)),
                ('room_group_name', models.CharField(max_length=100)),
            ],
        ),
    ]
