# Generated by Django 4.0.2 on 2022-04-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='roomgroupnametable',
            name='user_1',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='roomgroupnametable',
            name='user_2',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
