# Generated by Django 4.0.2 on 2022-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat_app', '0004_chattable_alter_roomgroupnametable_user_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chattable',
            name='userid',
            field=models.CharField(db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
