# Generated by Django 4.0.2 on 2022-04-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_chat_app', '0005_chattable_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chattable',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='chattable',
            name='is_seen',
        ),
        migrations.AlterField(
            model_name='chattable',
            name='userid',
            field=models.CharField(max_length=20),
        ),
    ]
