# Generated by Django 4.0.2 on 2022-03-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting_other_app', '0004_alter_staticsettingdata_consultancyservice_category_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticsettingdata',
            name='blog_tags_data',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
