# Generated by Django 4.0.2 on 2022-03-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting_other_app', '0005_staticsettingdata_blog_tags_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promo_code_data',
            old_name='promo_code_status',
            new_name='is_promo_code_active',
        ),
        migrations.RemoveField(
            model_name='promo_code_data',
            name='promo_code_end_date',
        ),
        migrations.RemoveField(
            model_name='promo_code_data',
            name='promo_code_start_date',
        ),
        migrations.AddField(
            model_name='promo_code_data',
            name='promo_code_amount',
            field=models.IntegerField(default=0),
        ),
    ]
