# Generated by Django 4.0.2 on 2022-03-21 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting_other_app', '0007_alter_promo_code_data_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promo_code_data',
            new_name='PromoCodeData',
        ),
        migrations.AlterModelTable(
            name='promocodedata',
            table=None,
        ),
    ]
