# Generated by Django 4.0.2 on 2022-04-02 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_setting_other_app', '0012_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='terget_user',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notification_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
