# Generated by Django 4.0.2 on 2022-04-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting_other_app', '0013_remove_notification_terget_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='userid',
        ),
    ]
