# Generated by Django 4.0.2 on 2022-04-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_setting_other_app', '0014_rename_user_notification_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_settings',
            old_name='user',
            new_name='userid',
        ),
    ]
