# Generated by Django 4.0.2 on 2022-02-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
    ]
