# Generated by Django 4.0.2 on 2022-03-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0006_alter_user_user_photopath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_fullname',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
