# Generated by Django 4.0.2 on 2022-03-27 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0019_remove_phoneotp_user_phoneotp_user_callphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 19, 45, 21, 523589)),
        ),
    ]
