# Generated by Django 4.0.2 on 2022-03-29 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0022_alter_phoneotp_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 0, 29, 56, 938268)),
        ),
    ]
