# Generated by Django 4.0.2 on 2022-02-27 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile_app', '0002_alter_user_socialaccount_and_about_user_whatsapp_visibility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_idverification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user_permanent_resident', models.BooleanField(default=False)),
                ('user_verify_id_type', models.CharField(blank=True, max_length=200, null=True)),
                ('user_verify_passportphoto_path', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_edu_degree', models.CharField(blank=True, max_length=200, null=True)),
                ('user_edu_institutename', models.CharField(blank=True, max_length=200, null=True)),
                ('user_edu_startdate', models.DateField(blank=True, null=True)),
                ('user_edu_enddate', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
