# Generated by Django 4.0.2 on 2022-02-27 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile_app', '0003_user_idverification_user_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_socialaccount_and_about',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
