# Generated by Django 4.0.2 on 2022-03-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile_app', '0007_alter_user_education_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_socialaccount_and_about',
            name='user_immo_visibility',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user_socialaccount_and_about',
            name='user_viber_visibility',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
